name: Build options

on: [push]

jobs:    
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: '[16.4,16.5)'
    - name: Download OpenCV
      working-directory: scripts/windows
      shell: bash
      run: |
        download.bat options\options_opencv4.5.0_contrib_vc16.txt
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download OpenCV
      working-directory: scripts
      run: |
        ./download.sh options/options_opencv4.5.0_contrib_vc16.txt