name: Build non-CUDA options

on: [push]

jobs:    
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download OpenCV repo/s
      working-directory: scripts/windows
      shell: cmd
      run: .\download.bat options\options_opencv4.9.0_contrib_vc16.txt
    - name: Build OpenCV
      working-directory: scripts/windows
      shell: cmd
      run: .\build.bat options\options_opencv4.9.0_contrib_vc16.txt
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build artifact
        path: install
  
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-23.04]
    steps:
    - uses: actions/checkout@v2
    - name: Download OpenCV repo/s
      working-directory: scripts/linux
      run: |
        ./download.sh options/options_opencv4.9.0_contrib_vc16.txt
    - name: Build OpenCV
      working-directory: scripts/linux
      run: |
        ./build.sh options/options_opencv4.9.0_contrib_vc16.txt
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build artifact
        path: install
